name: Test
on:
  push:
    branches:
      - master
    paths:
      - test_dent*
      - dent*
  pull_request:
    paths:
      - test_dent*
      - dent*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tests
        run: make test

